### ISSUE TITLE
Crash after  exceed the max request per minute

### ISSUE THREAD

**Issue by yagop** [SaltwaterC/virustotal.js#1]
Unhandled error when the maximum request per minute (4 for public API) is exceed.

```
/home/yago/Programacion/virustotal-test/node_modules/virustotal.js/lib/virustotal.js:104
        jsonHandler(res.buffer.toString(), callback);
                               ^
TypeError: Cannot call method 'toString' of undefined
    at /home/yago/Programacion/virustotal-test/node_modules/virustotal.js/lib/virustotal.js:104:26
    at /home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/main.js:59:6
    at Request.finish (/home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/request.js:737:3)
    at Request.saveBuffer (/home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/request.js:116:8)
    at /home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/main.js:53:13
    at Request.success (/home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/request.js:722:3)
    at ClientRequest.<anonymous> (/home/yago/Programacion/virustotal-test/node_modules/virustotal.js/node_modules/http-request/lib/request.js:371:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
```

And my test case:

``` js
var virustotal = require('virustotal.js');
virustotal.setKey('__PUBLIC_API_KEY__');

for (var i = 0; i < 9; i++) { 
    virustotal.getUrlReport('google.com', function (err, res) {
        if (err) {
            console.error(err);
            return;
        }

        console.log(res);
    });
}
```

**Comment by SaltwaterC** [comment]
Thanks. The issue is in [http-request](https://github.com/SaltwaterC/http-request/blob/8a6698a7fa41096b91327e3e910988f838756518/lib/request.js#L121). I'll need to see why it is failing as regardless of the response body the response.buffer should be there. It defaults to an empty Buffer object.

**Comment by SaltwaterC** [comment]
I was wrong. http-request does what it supposed to. The VT API doesn't. For API quota limits it starts to return 204 responses instead of using a proper error response. I made a patch, but I'll need to test more as your script hangs the event loop. It doesn't happen with a private API key where all the requests finish successfully, only with a public API where the quota is actually in use.

**Comment by SaltwaterC** [comment]
I did some work over the previous issue I was talking about. The event loop hangs when a 204 response is received, but the process exits after a while. The issue is unrelated to this library. I'll need to do some more debugging to see if things can be improved.
